/* ======================================================
     PROYECTO FINAL - MANUELA GIRALDO Y SOPHIA MATEUS
     SISTEMA DE GESTIÓN - CLUB DE PILATES Y YOGA 
     DDL - Definición de Tablas y Restricciones
   ====================================================== */

SET DEFINE OFF;

-- ELIMINAMOS LAS TABLAS EN ORDEN DE DEPENDENCIAS POR SI YA EXISTEN
DROP TABLE py_pagos CASCADE CONSTRAINTS;
DROP TABLE py_inscripciones CASCADE CONSTRAINTS;
DROP TABLE py_clases CASCADE CONSTRAINTS;
DROP TABLE py_membresias CASCADE CONSTRAINTS;
DROP TABLE py_miembros CASCADE CONSTRAINTS;


-- 1. MIEMBROS
CREATE TABLE py_miembros (
    miembro_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo_doc       VARCHAR2(5) NOT NULL,
    num_doc        VARCHAR2(20) NOT NULL,
    nombre         VARCHAR2(50) NOT NULL,
    email          VARCHAR2(50),
    fecha_registro DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    estado         VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,
    
    CONSTRAINT pk_py_miembros PRIMARY KEY (miembro_id),
    CONSTRAINT uq_py_miembro_doc UNIQUE (tipo_doc, num_doc),
    CONSTRAINT ck_py_miembro_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'POTENCIAL'))
);


-- 2. MEMBRESIAS
CREATE TABLE py_membresias (
    membresia_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    miembro_id     NUMBER NOT NULL,
    tipo_pase      VARCHAR2(30) NOT NULL,
    valor_pase     NUMBER(10, 2) NOT NULL,
    fecha_inicio   DATE NOT NULL,
    fecha_corte    DATE NOT NULL,
    estado_pago    VARCHAR2(20) DEFAULT 'NO PAGADA' NOT NULL,
    saldo_pendiente NUMBER(10, 2) DEFAULT 0 NOT NULL,
    
    CONSTRAINT pk_py_membresias PRIMARY KEY (membresia_id),
    CONSTRAINT fk_py_mem_miembro FOREIGN KEY (miembro_id) REFERENCES py_miembros (miembro_id),
    CONSTRAINT ck_py_mem_valor CHECK (valor_pase >= 0),
    CONSTRAINT ck_py_mem_saldo CHECK (saldo_pendiente >= 0),
    CONSTRAINT ck_py_mem_tipo_pase CHECK (tipo_pase IN ('PILATES MENSUAL', 'YOGA MENSUAL', 'VIP ANUAL', 'DAILY PASS', 'CORTESIA')),
    CONSTRAINT ck_py_mem_est_pago CHECK (estado_pago IN ('PAGADA', 'PAGO PARCIAL', 'NO PAGADA'))
);


-- 3. CLASES
CREATE TABLE py_clases (
    clase_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    disciplina     VARCHAR2(20) NOT NULL,
    fecha_clase    DATE NOT NULL,
    horario        VARCHAR2(15) NOT NULL,
    cupo_maximo    NUMBER(2) NOT NULL,
    cargo_inasist  NUMBER(10, 2) DEFAULT 15000 NOT NULL,
    
    CONSTRAINT pk_py_clases PRIMARY KEY (clase_id),
    CONSTRAINT ck_py_clase_disci CHECK (disciplina IN ('REFORMER PILATES', 'MAT PILATES', 'MAT YOGA', 'HOT YOGA', 'PUPPY YOGA')),
    CONSTRAINT ck_py_clase_cupo CHECK (cupo_maximo > 0),
    CONSTRAINT ck_py_clase_cargo CHECK (cargo_inasist >= 0)
);


-- 4. INSCRIPCIONES
CREATE TABLE py_inscripciones (
    inscripcion_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    miembro_id     NUMBER NOT NULL,
    clase_id       NUMBER NOT NULL,
    fecha_registro DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    estado_asist   VARCHAR2(20) DEFAULT 'RESERVADO' NOT NULL,
    
    CONSTRAINT pk_py_inscripciones PRIMARY KEY (inscripcion_id),
    CONSTRAINT fk_py_insc_miembro FOREIGN KEY (miembro_id) REFERENCES py_miembros (miembro_id),
    CONSTRAINT fk_py_insc_clase FOREIGN KEY (clase_id) REFERENCES py_clases (clase_id),
    CONSTRAINT uq_py_insc_miembro_clase UNIQUE (miembro_id, clase_id),
    CONSTRAINT ck_py_insc_estado CHECK (estado_asist IN ('RESERVADO', 'ASISTIÓ', 'NO ASISTIÓ'))
);


-- 5. PAGOS
CREATE TABLE py_pagos (
    pago_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    membresia_id   NUMBER NOT NULL,
    fecha_pago     DATE NOT NULL,
    monto_pago     NUMBER(12, 2) NOT NULL,
    canal_pago     VARCHAR2(30) DEFAULT 'TRANSFERENCIA' NOT NULL,
    referencia     VARCHAR2(50),
    
    CONSTRAINT pk_py_pagos PRIMARY KEY (pago_id),
    CONSTRAINT fk_py_pago_membresia FOREIGN KEY (membresia_id) REFERENCES py_membresias (membresia_id),
    CONSTRAINT ck_py_pago_monto CHECK (monto_pago >= 0)
);

COMMIT;
